export const COMPILATION_OF_CASE_NOTES = '11257';
export const COPY_OF_YOUR_ALLEGORICAL_SATIRE = '633';
export const COPY_OF_YOUR_EPIC_POETIC_CYCLE = '631';
export const COPY_OF_YOUR_GOTHIC_ROMANCE = '628';
export const COPY_OF_YOUR_TALE_OF_THE_FUTURE = '629';
export const ENTRY_IN_SLOWCAKES_EXCEPTIONALS = '752';
export const MERITORIOUS_COPY = '903';
export const NOTES_ON_THE_CASE_OF_THE_SPECULATIVE_ARACHNID = '693';
export const SALACIOUS_COPY = '905';
export const OUTLANDISH_COPY = '904';
export const O_BOYLES_PRACTICAL_PRIMER = '756';
export const PAGE_FROM_THE_LIBER_VISIONIS = '619';
export const PAGE_OF_CRYPTOPALAEONTOLOGICAL_NOTES = '896';
export const PAGE_OF_PRELAPSARIAN_ARCHAEOLOGICAL_NOTES = '898';
export const PAGE_OF_THEOSOPHISTICAL_NOTES = '897';
export const VOLUME_OF_YOUR_CRYPTOPALAEONTOLOGICAL_WORK = '900';
export const VOLUME_OF_YOUR_PRELAPSARIAN_ARCHAEOLOGICAL_WORK = '901';
export const VOLUME_OF_YOUR_THEOSOPHISTICAL_WORK = '902';

export const USEFUL_ITEMS = [
  ENTRY_IN_SLOWCAKES_EXCEPTIONALS,
];
