/* Works from Court */

export const COPY_OF_YOUR_ALLEGORICAL_SATIRE = '633';
export const COPY_OF_YOUR_BAZAARINE_TALE = 134899;
export const COPY_OF_YOUR_EPIC_POETIC_CYCLE = '631';
export const COPY_OF_YOUR_GOTHIC_ROMANCE = '628';
export const COPY_OF_YOUR_NOCTURNAL_RHAPSODY = 134942;
export const COPY_OF_YOUR_ODE_TO_THE_ELDER_CONTINENT = 134941;
export const COPY_OF_YOUR_PATRIOTIC_ADVENTURE = 630;
export const COPY_OF_YOUR_TALE_FOR_THE_PEOPLE = 134898;
export const COPY_OF_YOUR_TALE_OF_ESPIONAGE = 134897;
export const COPY_OF_YOUR_TALE_OF_THE_FUTURE = '629';
export const COPY_OF_YOUR_TRAGEDY_OF_ROMANCE = 632;
export const COPY_OF_YOUR_ZEEFARING_EPIC = 134940;

/* Short stories */

export const UNLOVED_SHORT_STORY = 18379;
export const SHORT_STORY = 18101;
export const COMPETENT_SHORT_STORY = 18100;
export const COMPELLING_SHORT_STORY = 18308;
export const THRILLING_SHORT_STORY = 18309;
export const EXCEPTIONAL_SHORT_STORY = 18310;
export const EXTRAORDINARY_SHORT_STORY = 18311;
export const MASTERFUL_SHORT_STORY = 18312;
export const CELEBRATED_SHORT_STORY = 18396;
export const CLASSIC_SHORT_STORY = 18381;

/* Scientific works */

export const PAGE_OF_CRYPTOPALAEONTOLOGICAL_NOTES = '896';
export const PAGE_OF_PRELAPSARIAN_ARCHAEOLOGICAL_NOTES = '898';
export const PAGE_OF_THEOSOPHISTICAL_NOTES = '897';

export const VOLUME_OF_YOUR_CRYPTOPALAEONTOLOGICAL_WORK = '900';
export const VOLUME_OF_YOUR_PRELAPSARIAN_ARCHAEOLOGICAL_WORK = '901';
export const VOLUME_OF_YOUR_THEOSOPHISTICAL_WORK = '902';

/* Newspaper copy */

export const MERITORIOUS_COPY = '903';
export const OUTLANDISH_COPY = '904';
export const SALACIOUS_COPY = '905';

/* Misc. */
export const BOOK_OF_HIDDEN_BODIES = 746;
export const COMPILATION_OF_CASE_NOTES = '11257';
export const ILLICIT_VOLUME_OF_UNEXPECTEDLY_RACY_FUNGAL_THEMED_POETRY = 116304;
export const NOTES_ON_THE_CASE_OF_THE_SPECULATIVE_ARACHNID = '693';
export const ON_THE_MALADIES_OF_GOATS_VOLUME_1 = 398;
export const TEAR_DROWNED_COLLECTION_OF_INCOMPREHENSIBLE_LOVE_POEMS = 107623;

/* Green-bordered stuff */
export const PAGE_FROM_THE_LIBER_VISIONIS = '619';
export const ENTRY_IN_SLOWCAKES_EXCEPTIONALS = '752';
export const O_BOYLES_PRACTICAL_PRIMER = '756';
